comm <- read.csv("data/cestes/comm.csv")
envir <- read.csv("data/cestes/envir.csv")
comm.pa <- comm[, -1] > 0
rich <- apply(X = comm.pa, MARGIN = 1, FUN = sum)
head(rich)
summary(rich)
boxplot(rich)
?par
boxplot(rich, las = 1)
localidades <- cbind(envir, rich)
head(localidades)
riqsilt <- lm(rich ~ Silt, data = localidades)
riqclay <- lm(rich ~ Clay, data = localidades)
riqsand <- lm(rich ~ Sand, data = localidades)
coef_s <- coef(riqsilt)
coef_c <- coef(riqclay)
coef_d <- coef(riqsand)
limy <- c(min(localidades$rich), max(localidades$rich))
limx <- c(min(localidades[,c("Clay", "Sand", "Silt")]), max(localidades[,c("Clay", "Sand", "Silt")]))
laby <- "Riqueza de espécies"
par(mfrow = c(1, 3),las = 1,bty = "l")
plot(rich ~ Silt, data = localidades, col = "tomato", ylim = limy, xlim = limx, ylab = laby, xlab = "Teor de Silte (%)")
abline(a = coef_s[1], b = coef_s[2], col = 'tomato', lwd = 2)
mtext("A", 3, adj = 0, font = 2)
plot(rich ~ Clay, data = localidades, col = "navy", ylim = limy, xlim = limx, ylab = "", xlab = "Teor de Argila (%)")
mtext("B", 3, adj = 0, font = 2)

abline(a = coef_c[1], b = coef_c[2], col = 'navy',lwd = 2)
plot(rich ~ Sand, data = localidades, col = "dodgerblue", ylim = limy, xlim = limx, ylab = "", xlab = "Teor de Areia (%)")
mtext("C", 3, adj = 0, font = 2)
abline(a = coef_d[1], b = coef_d[2], col = 'dodgerblue',lwd = 2)

png("figs/figura01.png", res = 300, width = 2400, height = 1200)
par(mfrow = c(1, 3),las = 1,bty = "l")

plot(rich ~ Silt, data = localidades, col = "tomato", ylim = limy, xlim = limx, ylab = laby, xlab = "Teor de Silte (%)")
abline(a = coef_s[1], b = coef_s[2], col = 'tomato', lwd = 2)
mtext("A", 3, adj = 0, font = 2)

plot(rich ~ Clay, data = localidades,col = "navy", ylim = limy, xlim = limx, ylab = "", xlab = "Teor de Argila (%)")
mtext("B", 3, adj = 0, font = 2)
abline(a = coef_c[1], b = coef_c[2], col = 'navy',lwd = 2)

plot(rich ~ Sand, data = localidades, col = "dodgerblue", ylim = limy, xlim = limx, ylab = "", xlab = "Teor de Areia (%)")
mtext("C", 3, adj = 0, font = 2)
abline(a = coef_d[1], b = coef_d[2], col = 'dodgerblue',lwd = 2)
dev.off()
